apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-perflab-data
  namespace: perflab
  labels:
    app: gpu-perflab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
